/*
 * generated by Xtext 2.10.0
 */
package org.alma.smalluml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmallUMLRuntimeModule extends AbstractSmallUMLRuntimeModule {
}
