<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smalluml" nsURI="http://www.univ-nantes.fr/smalluml" nsPrefix="smalluml">
  <eSubpackages name="types" nsURI="http://www.univ-nantes.fr/smalluml/types" nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Real" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnlimitedNatural" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//elements/NamedElement #//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          upperBound="-1" eType="#//types/String" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="elements" nsURI="http://www.univ-nantes.fr/smalluml/elements"
      nsPrefix="elements">
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//elements/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
          eType="#//elements/Class" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#//elements/Attribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
          eType="#//elements/Method" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//elements/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typedValue" lowerBound="1"
          eType="#//types/Type" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//elements/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnTypedValue" eType="#//types/Type"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//elements/Attribute" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="links" nsURI="http://www.univ-nantes.fr/smalluml/links" nsPrefix="links">
    <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//elements/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" lowerBound="1"
          eType="#//links/Cardinality" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//elements/Class"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//elements/Class" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cardinality">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
