/*
 * generated by Xtext 2.10.0
 */
package org.alma.uml.smalluml.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.alma.uml.smalluml.ide.contentassist.antlr.internal.InternalSmallUmlParser;
import org.alma.uml.smalluml.services.SmallUmlGrammarAccess;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class SmallUmlParser extends AbstractContentAssistParser {

	@Inject
	private SmallUmlGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSmallUmlParser createParser() {
		InternalSmallUmlParser result = new InternalSmallUmlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
					put(grammarAccess.getPackageAccess().getGroup_1(), "rule__Package__Group_1__0");
					put(grammarAccess.getPackageAccess().getGroup_2(), "rule__Package__Group_2__0");
					put(grammarAccess.getPackageAccess().getGroup_3(), "rule__Package__Group_3__0");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getClassAccess().getGroup_3(), "rule__Class__Group_3__0");
					put(grammarAccess.getClassAccess().getGroup_3_2(), "rule__Class__Group_3_2__0");
					put(grammarAccess.getClassAccess().getGroup_5(), "rule__Class__Group_5__0");
					put(grammarAccess.getClassAccess().getGroup_6(), "rule__Class__Group_6__0");
					put(grammarAccess.getRelationAccess().getGroup(), "rule__Relation__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getMethodAccess().getGroup_3(), "rule__Method__Group_3__0");
					put(grammarAccess.getMethodAccess().getGroup_3_1(), "rule__Method__Group_3_1__0");
					put(grammarAccess.getCardinalityAccess().getGroup(), "rule__Cardinality__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup(), "rule__Enumeration__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup_4(), "rule__Enumeration__Group_4__0");
					put(grammarAccess.getConcreteTypeAccess().getGroup(), "rule__ConcreteType__Group__0");
					put(grammarAccess.getPackageAccess().getClassAssignment_1_0(), "rule__Package__ClassAssignment_1_0");
					put(grammarAccess.getPackageAccess().getRelationAssignment_2_0(), "rule__Package__RelationAssignment_2_0");
					put(grammarAccess.getPackageAccess().getTypesAssignment_3_0(), "rule__Package__TypesAssignment_3_0");
					put(grammarAccess.getClassAccess().getIsAbstractAssignment_0(), "rule__Class__IsAbstractAssignment_0");
					put(grammarAccess.getClassAccess().getNameAssignment_2(), "rule__Class__NameAssignment_2");
					put(grammarAccess.getClassAccess().getParentsAssignment_3_1(), "rule__Class__ParentsAssignment_3_1");
					put(grammarAccess.getClassAccess().getParentsAssignment_3_2_1(), "rule__Class__ParentsAssignment_3_2_1");
					put(grammarAccess.getClassAccess().getAttributesAssignment_5_2(), "rule__Class__AttributesAssignment_5_2");
					put(grammarAccess.getClassAccess().getAttributesAssignment_5_3(), "rule__Class__AttributesAssignment_5_3");
					put(grammarAccess.getClassAccess().getMethodsAssignment_6_2(), "rule__Class__MethodsAssignment_6_2");
					put(grammarAccess.getClassAccess().getMethodsAssignment_6_3(), "rule__Class__MethodsAssignment_6_3");
					put(grammarAccess.getRelationAccess().getNameAssignment_1(), "rule__Relation__NameAssignment_1");
					put(grammarAccess.getRelationAccess().getFromAssignment_4(), "rule__Relation__FromAssignment_4");
					put(grammarAccess.getRelationAccess().getToAssignment_6(), "rule__Relation__ToAssignment_6");
					put(grammarAccess.getRelationAccess().getCardinalityAssignment_8(), "rule__Relation__CardinalityAssignment_8");
					put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
					put(grammarAccess.getAttributeAccess().getTypedValueAssignment_2(), "rule__Attribute__TypedValueAssignment_2");
					put(grammarAccess.getMethodAccess().getNameAssignment_1(), "rule__Method__NameAssignment_1");
					put(grammarAccess.getMethodAccess().getParametersAssignment_3_0(), "rule__Method__ParametersAssignment_3_0");
					put(grammarAccess.getMethodAccess().getParametersAssignment_3_1_1(), "rule__Method__ParametersAssignment_3_1_1");
					put(grammarAccess.getMethodAccess().getReturnTypedValueAssignment_6(), "rule__Method__ReturnTypedValueAssignment_6");
					put(grammarAccess.getCardinalityAccess().getLowerBoundAssignment_1(), "rule__Cardinality__LowerBoundAssignment_1");
					put(grammarAccess.getCardinalityAccess().getUpperBoundAssignment_3(), "rule__Cardinality__UpperBoundAssignment_3");
					put(grammarAccess.getEnumerationAccess().getNameAssignment_1(), "rule__Enumeration__NameAssignment_1");
					put(grammarAccess.getEnumerationAccess().getValueAssignment_3(), "rule__Enumeration__ValueAssignment_3");
					put(grammarAccess.getEnumerationAccess().getValueAssignment_4_1(), "rule__Enumeration__ValueAssignment_4_1");
					put(grammarAccess.getConcreteTypeAccess().getNameAssignment_2(), "rule__ConcreteType__NameAssignment_2");
					put(grammarAccess.getEnumerationElementAccess().getValueAssignment(), "rule__EnumerationElement__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalSmallUmlParser typedParser = (InternalSmallUmlParser) parser;
			typedParser.entryRulePackage();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SmallUmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmallUmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
