/**
 * generated by Xtext 2.10.0
 */
package org.alma.smalluml;

import org.alma.smalluml.AbstractSmallUMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallUMLRuntimeModule extends AbstractSmallUMLRuntimeModule {
}
