/*
 * generated by Xtext 2.10.0
 */
package org.alma.uml.smalluml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmallUmlRuntimeModule extends AbstractSmallUmlRuntimeModule {
}
