grammar org.alma.uml.smalluml.SmallUml with org.eclipse.xtext.common.Terminals

import "http://www.univ-nantes.fr/smalluml" 
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Package returns Package:
	{Package}
	( class+=Class ';' )*
	( relation+=Relation ';')*
	( types+=Type ';')*

;

Type returns Type:
	Enumeration | ConcreteType;

Class returns Class:
	(isAbstract?='Abstract')?
	'Class'
	name=ID ('extends' parents+=[Class] ( "," parents+=[Class])* )?
	'{'
		('attributes' '{' attributes+=Attribute ( attributes+=Attribute)* '}' )?
		('methods' '{' methods+=Method ( methods+=Method)* '}' )?
	'}';

Relation returns Relation:
	'Relation'
	name=ID
	'{'
		'from' from=[Class]
		'to' to=[Class]
		'cardinality' cardinality=Cardinality
	'}';

EString returns ecore::EString:
	STRING | ID;

EBoolean returns ecore::EBoolean:
	'true' | 'false';

Attribute returns Attribute:
	name=EString ':' typedValue=[Type] ';';

Method returns Method:
	{Method}
	name=ID '('( parameters+=Attribute ( "," parameters+=Attribute)*  )?')' ':' (returnTypedValue=[Type])? ';';


Cardinality returns Cardinality:
	'[' lowerBound=EInt',' upperBound=EInt']';

EInt returns ecore::EInt:
	'-'? INT;

Enumeration returns Enumeration:
	'Enumeration'
	name=ID
	'{'
		value+=EnumerationElement ( "," value+=EnumerationElement)*
	'}';

ConcreteType returns ConcreteType:
	{ConcreteType}
	'ConcreteType'
	name=EString;

EnumerationElement returns EnumerationElement:
	value=ID;
