/*
 * generated by Xtext 2.10.0
 */
package org.alma.uml.smalluml.ui.tests;

import com.google.inject.Injector;
import org.alma.uml.smalluml.ui.internal.SmallumlActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SmallUmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmallumlActivator.getInstance().getInjector("org.alma.uml.smalluml.SmallUml");
	}

}
